Hw task3
andreisavelyeu/nodejs-aws-be pull request #1
Opened 2021-04-07 21:52 UTC by andreisavelyeu

Front End

- pr: https://github.com/andreisavelyeu/nodejs-aws-fe/pull/2
- cloudfront: https://d3vf03n8aezsra.cloudfront.net/

Endpoints

- GET - https://ks1prj1wf4.execute-api.eu-west-1.amazonaws.com/dev/products
- GET by id - https://ks1prj1wf4.execute-api.eu-west-1.amazonaws.com/dev/products/cb534554-bb8e-4fd5-a839-e3b00e3447b0
- invalid id - https://ks1prj1wf4.execute-api.eu-west-1.amazonaws.com/dev/products/dasdada
- not found - https://ks1prj1wf4.execute-api.eu-west-1.amazonaws.com/dev/products/cb534554-bb8e-4fd5-a839-e3b00e3443b1

- getProducts and getProductById are returns correct code/response
- getProducts is integrated to front end app
- ES6 modules are used for product-service implementation
- Webpack is configured for product-service
- Lambda handlers are covered by basic UNIT tests (NO infrastructure logic is needed to be covered) (You may use JEST)
- Lambda handlers (getProducts, getProductsById) code is written not in 1 single module (file) and separated in codebase.
- Main error scenarious are handled by API ("Product not found" error, try catch blocks are used in lambda handlers).

2021-04-11 15:15 UTC, kzanton requested changes
"\_\_test__" - is very unusual to have python style naming for js projects

2021-04-11 15:21 UTC, kzanton commented on product-service/src/data/products.ts
> +interface Product {
It will be better to move the Interface definition to separated file

2021-04-11 15:25 UTC, kzanton commented on product-service/src/functions/getProductById/handler.ts
> +  const product = data.find((item) => item.id === id);
Asynchronous data loading is supposed

2021-04-11 15:28 UTC, kzanton commented on product-service/src/functions/getProductById/handler.ts
> +export const getProductById:
Try catch must be used in lambda handlers

2021-04-11 15:34 UTC, kzanton commented on product-service/src/functions/getProductById/handler.ts
> +    return formatJSONResponse({ body: JSON.stringify(product) });
Serialization is not needed here, it will be done in formatJSONResponse

2021-04-11 15:36 UTC, kzanton commented on product-service/src/functions/getProducts/handler.ts
> +export const getProducts = async () => {
Try catch must be used in lambda handlers

2021-04-11 15:36 UTC, kzanton commented on product-service/src/functions/getProducts/handler.ts
> +  const body = JSON.stringify(data);
Serialization is not needed here, it will be done in formatJSONResponse

2021-04-11 15:37 UTC, kzanton commented on product-service/src/functions/getProducts/handler.ts
> +  const body = JSON.stringify(data);
Asynchronous data loading is supposed

2021-04-17 21:38 UTC, andreisavelyeu commented on product-service/src/data/products.ts
> +interface Product {
Thanks a lot for the review, Anton!

2021-04-19 20:04 UTC, merged